version = 1

[[annotations]]
path = [
    ".gitignore",
    "REUSE.toml",
    "node_modules/**/*",
    "output/*",
    "package-lock.json",
    "package.json",
    "requirements.txt",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# This just serves to silence `reuse` — the copyright is incorrect.
[[annotations]]
path = [
    "node_modules/**/*",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "build/**/*",
]
SPDX-FileCopyrightText = "© 2024 Vlad-Stefan Harbuz <vlad@vladh.net>"
SPDX-License-Identifier = "Apache-2.0"
